version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.10.0

        working_directory: ~/repo

        steps:
            - add-ssh-keys:
                  fingerprints:
                      - 'fd:72:96:ac:ea:a7:07:7f:58:28:18:94:a5:65:76:74'
            - checkout

            - restore_cache:
                  keys:
                      - v7-dependencies-{{ checksum "package.json" }}
                      - v7-dependencies-

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v7-dependencies-{{ checksum "package.json" }}

            - run: yarn test
            - run: yarn chromatic test -a y9ydey6qsvf --exit-zero-on-changes
            - run: |
                  if [ $CIRCLE_BRANCH = "master" ]
                  then
                    yarn release
                  fi
